# Generated by Django 4.2 on 2023-09-03 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_alter_wordmeaning_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordmeaning',
            name='author',
        ),
    ]
