# Generated by Django 4.2 on 2023-09-03 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_remove_wordmeaning_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_examples', to='words.author', verbose_name='Author of meaning'),
        ),
    ]
